language: elixir
elixir:
  - 1.9.1
  - 1.8.2
  - 1.7.4
  - 1.6.6
otp_release:
  - 21.3
matrix:
  include:
    - elixir: 1.7.4
      otp_release: 19.3
    - elixir: 1.6.6
      otp_release: 19.3
services:
  - redis-server
script:
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
