name: Build

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }}
    strategy:
      matrix:
        elixir:
          - 1.14.4
        otp:
          - 25.3
          - 24.3
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
      - run: mix coveralls

  deploy:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
