name: Build

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 11 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }}
    strategy:
      matrix:
        elixir:
          - 1.14.4
          - 1.13.4
          - 1.12.3
          - 1.11.4
        otp:
          - 24.3
        include:
          - elixir: 1.14.4
            otp: 25.3
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
      - run: mix coveralls
